name: CI
on: [push]

jobs:
  test:
    name: hardhat tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18

      - name: install node deps
        run: yarn install --frozen-lockfile

      - name: check formatting
        run: yarn check:format

      - name: test
        run: yarn test
